image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: context
    path: .
outputs:
  - name: image
caches:
  - path: cache

platform: linux
run:
  path: build
